/** Theme-aware classes — colors from globals.css variables only */
export const UI = {
  card: "lw-card rounded-2xl p-5 shadow-sm",
  chartCard: "lw-card rounded-2xl p-5 shadow-sm",
  statCard: "lw-card rounded-xl p-4 shadow-sm",
  hero: "lw-hero rounded-2xl p-6 shadow-lg",
  planA: "lw-plan-a rounded-2xl p-5",
  planAEdit: "lw-plan-a-edit",
  planB: "lw-plan-b rounded-2xl p-5",
  planBEdit: "lw-plan-b rounded-2xl p-5 shadow-sm",
  loanField: "lw-loan-field",
  planC: "lw-plan-c rounded-2xl p-5 shadow-sm",
  title: "lw-title text-xl font-semibold",
  titleSm: "lw-title text-lg font-semibold",
  titleHero: "lw-title text-3xl font-bold",
  subtitle: "lw-muted mt-2",
  subtitleSm: "lw-muted mt-1 text-sm",
  label: "lw-label block text-sm font-medium",
  input: "lw-input mt-1 w-full rounded-md px-3 py-2 shadow-sm",
  inputInline: "lw-input w-full rounded-md px-3 py-2 shadow-sm",
  list: "mt-4 space-y-2 text-sm",
  tableHead: "lw-table-head",
  tableRow: "lw-table-row",
  btnSecondary: "lw-btn-secondary rounded-lg px-4 py-2 text-sm font-medium",
  btnHero: "lw-btn-hero inline-block rounded-md px-4 py-2 text-sm font-medium",
  btnPrimary: "inline-block rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500",
  link: "lw-link",
  success: "lw-success font-semibold",
  boxIndigo: "lw-box-indigo rounded-lg p-3",
  boxEmerald: "lw-box-emerald rounded-lg p-3",
  preset: "lw-preset rounded-lg px-3 py-2 text-left text-sm",
  accentStat: "lw-accent-stat text-2xl font-bold",
} as const;
